### ISSUE TITLE
Server crashes at startup

### ISSUE THREAD

**Issue by prodkid** [eidehua/More-Health-Enhanced#1]
This occurs. This seems like the repo for more health enhanced. Let me know if it's not xD.
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 1/9/15 1:49 PM
Description: Exception in server tick loop

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraft/client/settings/KeyBinding
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:692)
    at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
    at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:324)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:280)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:620)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/settings/KeyBinding
    at com.nohero.morehealth.mod_moreHealthEnhanced.load(mod_moreHealthEnhanced.java:174)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:691)
    ... 5 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.settings.KeyBinding
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 32 more
Caused by: java.lang.NullPointerException
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_71, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 3003617328 bytes (2864 MB) / 4097835008 bytes (3908 MB) up to 7635730432 bytes (7282 MB)
    JVM Flags: 4 total; -Xmx8192M -Xms2048M -XX:PermSize=256M -XX:MaxPermSize=512M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.85.1264 git-Cauldron-MCPC-Plus-1.7.10-1.1231.04.209 (MC: 1.7.10) (API v1.7.10-R0.1-SNAPSHOT) Minecraft Forge 10.13.2.1264 65 mods loaded, 65 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    FML{7.10.85.1264} [Forge Mod Loader](cauldron-server.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Forge{10.13.2.1264} [Minecraft Forge](cauldron-server.jar) Unloaded->Constructed->Pre-initialized->Initialized
    CodeChickenCore{1.0.4.29} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ivtoolkit{1.0.2} [IvToolkit](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MobiusCore{1.2.3} [MobiusCore](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    NotEnoughItems{1.0.4.83} [Not Enough Items](NotEnoughItems.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    malisiscore{1.7.10-0.10.3+unknown-b0.git-unknown} [Malisis Core](MalisisCore.jar) Unloaded->Constructed->Pre-initialized->Initialized
    psychedelicraftcore{1.4} [Psychedelicraft Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    act{0.0.2a_1.7.10} [AdminCommandsToolbox](AdminCommandsToolbox-0.0.2a_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    AnimationAPI{1.2.4} [AnimationAPI](AnimationAPI.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships](ArchimedesShips.jar) Unloaded->Constructed->Pre-initialized->Initialized
    arsmagica2{1.4.0.005} [Ars Magica 2](ArsMagica2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    battlegear2{1.0.6.3} [Mine & Blade Battlegear 2 - Bullseye](Battlegear2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BattleTowers{1.4.9} [Battle Towers](BattleTowers.jar) Unloaded->Constructed->Pre-initialized->Initialized
    betterrecords{1.7.10-1.1.9} [Better Records](betterrecords.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BiblioCraft{1.9.2} [BiblioCraft](BiblioCraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BiomesOPlenty{2.1.0} [Biomes O' Plenty](BiomesOPlenty.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BiblioWoodsBoP{1.9} [BiblioWoods Biomes O'Plenty Edition](BiblioWoodsBiomesOPlenty.jar) Unloaded->Constructed->Pre-initialized->Initialized
    AWWayofTime{v1.3.0a} [Blood Magic: Alchemical Wizardry](BloodMagic.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Thaumcraft{4.2.3.0} [Thaumcraft](Thaumcraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Botania{r1.3-149} [Botania](Botania.jar) Unloaded->Constructed->Pre-initialized->Initialized
    CarpentersBlocks{3.3.3} [Carpenter's Blocks](CarpentersBlocks.jar) Unloaded->Constructed->Pre-initialized->Initialized
    chisel{2.2.1} [Chisel](Chisel.jar) Unloaded->Constructed->Pre-initialized->Initialized
    chococraft{4.1.4} [Clienthax's ChocoCraft](ChocoCraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    customnpcs{1.7.10b} [CustomNpcs](CustomNPCs.jar) Unloaded->Constructed->Pre-initialized->Initialized
    props{1.11} [Decocraft](Decocraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    dungeonpack{1.7.10-1.0} [Dungeon Pack](dungeonpack.jar) Unloaded->Constructed->Pre-initialized->Initialized
    eplus{3.0.2-d} [Enchanting Plus](EnchantingPlus.jar) Unloaded->Constructed->Pre-initialized->Initialized
    farlanders{1.2b} [The Farlanders](farlanders.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Steamcraft{0.27.3} [Flaxbeard's Steam Power](FlaxbeardsSteamPower.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ThaumicTinkerer{unspecified} [Thaumic Tinkerer](ThaumicTinkerer.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ForbiddenMagic{1.7.10-0.552} [Forbidden Magic](ForbiddenMagic.jar) Unloaded->Constructed->Pre-initialized->Initialized
    GraveStone{2.11.1} [GraveStone](GraveStone.jar) Unloaded->Constructed->Pre-initialized->Initialized
    iChunUtil{4.1.3} [iChunUtil](iChunUtil.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Hats{4.0.1} [Hats](Hats.jar) Unloaded->Constructed->Pre-initialized->Initialized
    InfernalMobs{1.5.7} [Infernal Mobs](InfernalMobs.jar) Unloaded->Constructed->Pre-initialized->Initialized
    JABBA{1.2.0a} [JABBA](Jabba.jar) Unloaded->Constructed->Pre-initialized->Initialized
    malisisdoors{1.7.10-1.3.3} [Malisis' Doors](MalisisDoors.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Mantle{1.7.10-0.3.2.jenkins184} [Mantle](Mantle.jar) Unloaded->Constructed->Pre-initialized->Initialized
    mod_MedievalWars{0.1} [Medievalwars](Medievalwars.jar) Unloaded->Constructed->Pre-initialized->Initialized
    radixcore{1.3.4} [RadixCore](RadixCore.jar) Unloaded->Constructed->Pre-initialized->Initialized
    mca{4.1.5} [Minecraft Comes Alive](MinecraftComesAlive.jar) Unloaded->Constructed->Pre-initialized->Initialized
    AS_Minions{1.9.4} [Minions](Minions.jar) Unloaded->Constructed->Pre-initialized->Initialized
    morehealth{6.2} [More Health Forge](MoreHealthEnchanted.zip) Unloaded->Constructed->Pre-initialized->Errored
    moreplayermodels{1.7.10b} [MorePlayerModels](MorePlayerModels.jar) Unloaded->Constructed->Pre-initialized->Initialized
    mam{1.7.10-1.0.2} [Myths & Monsters Mod](mythsandmonsters.jar) Unloaded->Constructed->Pre-initialized->Initialized
    necromancy{1.7.0} [Necromancy](Necromancy.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MapWriter{2.1.1} [MapWriter](Opis-1.2.3_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Opis{1.2.3} [Opis](Opis-1.2.3_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    harvestcraft{1.7.10b} [Pam's HarvestCraft](PamsHarvestCraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ProjectZulu|Core{1.7.10-1.3f} [Project Zulu](ProjectZulu.jar) Unloaded->Constructed->Pre-initialized->Initialized
    psychedelicraft{1.5} [Psychedelicraft](Psychedelicraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Roguelike{1.3.5} [Roguelike Dungeons](roguelike.jar) Unloaded->Constructed->Pre-initialized->Initialized
    AS_Ruins{13.8} [Ruins Spawning System](Ruins.jar) Unloaded->Constructed->Pre-initialized->Initialized
    secretroomsmod{4.7.1} [The SecretRoomsMod](secretroomsmod.jar) Unloaded->Constructed->Pre-initialized->Initialized
    TConstruct{1.7.10-1.8.2.build858} [Tinkers' Construct](TConstruct.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Trapcraft{v2.2.1a} [Trapcraft](Trapcraft.zip) Unloaded->Constructed->Pre-initialized->Initialized
    bspkrsCore{6.14} [bspkrsCore]([1.7.10]bspkrsCore-universal-6.14.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Treecapitator{1.7.2} [Treecapitator](Treecapitator.jar) Unloaded->Constructed->Pre-initialized->Initialized
    TwilightForest{2.3.2} [The Twilight Forest](twilightforest.jar) Unloaded->Constructed->Pre-initialized->Initialized
    witchery{0.21.2} [Witchery](witchery.jar) Unloaded->Constructed->Pre-initialized->Initialized
    yegamolchattels{1.1} [Ye Gamol Chattels](YeGamolChattels.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: bukkit
    TConstruct Environment: Environment healthy.
    Profiler Position: N/A (disabled)
    Player Count: 0 / 10; []
    Is Modded: Definitely; Server brand changed to 'cauldron,craftbukkit,mcpc,fml,forge'
    Type: Dedicated Server (map_server.txt)

**Comment by eidehua** [comment]
Will fix, thanks!

**Comment by prodkid** [comment]
Ah you're not dead!  Good to here from you lol. Awesome thanks :)

**Comment by eidehua** [comment]
Ok I've id'd the issue, I'll get a fixed version tomorrow

**Comment by eidehua** [comment]
Closed with https://github.com/eidehua/More-Health-Enhanced/commit/56c128f8074b9db6987a48d888daa416b12266be
