### ISSUE TITLE
Continuation

### ISSUE THREAD

**Issue by FireController1847** [eidehua/More-Health-Enhanced#10]
Hai! Me and a friend have began creating a mod called LevelHearts, and due to the fact it's based a lot off of your code, I should ask you for permission to create it (and if you want, for us to become the new owners). Can't wait to hear back!

**Comment by eidehua** [comment]
Sure, just be sure to include this as a source/reference maybe somewhere in your readme.

**Comment by FireController1847** [comment]
@eidehua Awesome! Thank you so much! I'll be sure to give you credit! (Also, if you have a CurseForge account I'll add you as "Previous Owner" to the project.) Here's a link. If there's something you want me to add/remove, just tell me! ^-^

https://minecraft.curseforge.com/projects/levelhearts

**Comment by FireController1847** [comment]
@eidehua Here's a link. If there's something you want me to add/remove, just tell me! ^-^

**Comment by FireController1847** [comment]
@eidehua Uh.. All of your previous versions have gone 404 on Dropbox. Do you happen to have any backups>

**Comment by FireController1847** [comment]
If you bring them back and I have your permission, I'll upload your mod to CurseForge where you can know the files won't go 404.
