### ISSUE TITLE
Look like the mod don't start in my serveur; how active it

### ISSUE THREAD

**Issue by gamersalpha** [eidehua/More-Health-Enhanced#11]
Hello i put the mod on my server, but i stil have all my hearth ?

how to activate the mod on serveur please.

i put the files : levelhearts-1.12.2-1.1.0.jar on the directory : 
![image](https://user-images.githubusercontent.com/32466950/62971220-9250c880-be11-11e9-885e-42abc9467874.png)

but when i play on the server i got all my heart : 

![Uploading 20190813213106_1.jpg…]()

**Comment by FireController1847** [comment]
You are asking about an issue for LevelHearts, which is the new remastered version of this mod. Please post the issue there and NOT here, as this is not the right place for it.
